FROM nginx:latest

WORKDIR /

# 기본 설정 파일 제거
RUN rm -rf /etc/nginx/conf.d/default.conf

# Streamlit 설정 파일 복사
COPY streamlit.conf /etc/nginx/conf.d/

# 로그 디렉토리 권한 설정
RUN mkdir -p /var/log/nginx && \
    chmod -R 755 /var/log/nginx